/**
 * Infrastructure Self-Modification
 *
 * Enables agents to propose and apply infrastructure changes via GitOps PRs,
 * bounded by Cedar policies with three escalation modes.
 */

import { CodeCommitClient, CreateBranchCommand, PutFileCommand, MergeBranchesByFastForwardCommand, CreatePullRequestCommand, GetBranchCommand } from '@aws-sdk/client-codecommit';
import type {
  InfrastructureChangeProposal,
  InfrastructureChangeResult,
  IaCChangeType,
  SelfHealAction,
} from './types';
import type { EvolutionSafetyHarness } from './safety-harness';

/**
 * Infrastructure modifier with GitOps workflow
 */
export class InfrastructureModifier {
  private codecommit: CodeCommitClient;
  private safetyHarness: EvolutionSafetyHarness;
  private repositoryName: string;

  constructor(params: {
    repositoryName: string;
    safetyHarness: EvolutionSafetyHarness;
  }) {
    this.repositoryName = params.repositoryName;
    this.safetyHarness = params.safetyHarness;
    this.codecommit = new CodeCommitClient({});
  }

  /**
   * Propose an infrastructure change via GitOps PR
   */
  async proposeInfrastructureChange(
    proposal: InfrastructureChangeProposal
  ): Promise<InfrastructureChangeResult> {
    // Step 1: Validate operation safety
    const safetyCheck = this.safetyHarness.validateInfraOperation(proposal.changeType);
    if (!safetyCheck.safe) {
      return {
        status: 'denied',
        cedarDecision: 'DENY',
        changeType: proposal.changeType,
        reason: safetyCheck.reason,
      };
    }

    // Step 2: Generate IaC diff
    const iacDiff = await this.generateCDKDiff(proposal);

    // Step 3: Evaluate Cedar policy
    const authResult = await this.safetyHarness.authorize({
      tenantId: proposal.tenantId,
      agentId: proposal.tenantId, // Using tenant as agent ID
      action: 'create',
      eventType: 'evolution_infra',
      changeType: proposal.changeType,
      estimatedMonthlyCostDelta: proposal.estimatedMonthlyCostDelta,
      humanApproved: false,
    });

    const canAutoApply = authResult.decision === 'ALLOW';

    // Step 4: Create branch
    const branchName = `evolution/${proposal.tenantId}/${proposal.changeType}-${Date.now()}`;

    try {
      const mainHead = await this.getMainHead();

      await this.codecommit.send(
        new CreateBranchCommand({
          repositoryName: this.repositoryName,
          branchName,
          commitId: mainHead,
        })
      );

      // Step 5: Commit changes
      await this.codecommit.send(
        new PutFileCommand({
          repositoryName: this.repositoryName,
          branchName,
          fileContent: Buffer.from(iacDiff),
          filePath: `tenants/${proposal.tenantId}/config.ts`,
          commitMessage: `[evolution] ${proposal.changeDescription}`,
        })
      );

      // Step 6: Auto-apply or create PR
      if (canAutoApply) {
        // Auto-merge and trigger pipeline
        await this.codecommit.send(
          new MergeBranchesByFastForwardCommand({
            repositoryName: this.repositoryName,
            sourceCommitSpecifier: branchName,
            destinationCommitSpecifier: 'main',
          })
        );

        // Increment rate limit counters
        await this.safetyHarness.incrementRateLimitCounters(
          proposal.tenantId,
          'evolution_infra'
        );

        return {
          status: 'auto_applied',
          branch: branchName,
          cedarDecision: 'ALLOW',
          changeType: proposal.changeType,
        };
      } else {
        // Create PR for human review
        const pr = await this.codecommit.send(
          new CreatePullRequestCommand({
            title: `[Evolution] ${proposal.changeDescription}`,
            description: `Auto-generated by evolution engine.

Tenant: ${proposal.tenantId}
Change type: ${proposal.changeType}
Cedar decision: DENY (requires human approval)
Estimated cost impact: $${proposal.estimatedMonthlyCostDelta}/month

\`\`\`diff
${iacDiff}
\`\`\``,
            targets: [
              {
                repositoryName: this.repositoryName,
                sourceReference: branchName,
                destinationReference: 'main',
              },
            ],
          })
        );

        return {
          status: 'pr_created',
          branch: branchName,
          prId: pr.pullRequest?.pullRequestId,
          cedarDecision: 'DENY',
          changeType: proposal.changeType,
          reason: 'Change requires human approval',
        };
      }
    } catch (error) {
      console.error('Infrastructure change failed:', error);
      return {
        status: 'denied',
        cedarDecision: 'DENY',
        changeType: proposal.changeType,
        reason: error instanceof Error ? error.message : 'Unknown error',
      };
    }
  }

  /**
   * Execute emergency self-heal action
   */
  async executeSelfHeal(params: {
    tenantId: string;
    runtimeId: string;
    action: SelfHealAction;
    healthStatus: string;
  }): Promise<{ success: boolean; message: string }> {
    // Authorize emergency heal
    const authResult = await this.safetyHarness.authorize({
      tenantId: params.tenantId,
      agentId: params.tenantId,
      action: 'update',
      eventType: 'evolution_infra',
      estimatedMonthlyCostDelta: 0, // No cost impact for emergency heals
    });

    if (authResult.decision !== 'ALLOW') {
      return {
        success: false,
        message: 'Emergency heal not authorized by Cedar policy',
      };
    }

    // Execute heal action based on type
    switch (params.action) {
      case 'restart_runtime':
        return await this.restartRuntime(params.runtimeId);
      case 'clear_cache':
        return await this.clearCache(params.runtimeId);
      case 'reset_session':
        return await this.resetSession(params.runtimeId);
      default:
        return {
          success: false,
          message: `Unknown heal action: ${params.action}`,
        };
    }
  }

  /**
   * Estimate cost impact of a proposed change
   */
  estimateCostImpact(proposal: InfrastructureChangeProposal): number {
    // Placeholder: In production, would analyze CDK diff and compute cost delta
    const costEstimates: Record<IaCChangeType, number> = {
      scale_horizontal: 50, // $50/month for one additional instance
      scale_vertical: 30,   // $30/month for instance size upgrade
      update_env_var: 0,
      rotate_secret: 0,
      add_tool: 10,         // $10/month for tool resources
      update_config: 0,
    };

    return costEstimates[proposal.changeType] || 0;
  }

  // Private helper methods

  private async generateCDKDiff(
    proposal: InfrastructureChangeProposal
  ): Promise<string> {
    // Placeholder: In production, would generate actual CDK TypeScript code
    // based on change type and parameters

    const changeTypeTemplates: Record<IaCChangeType, (p: any) => string> = {
      scale_horizontal: (p) =>
        `// Scale ECS service horizontally
const service = stack.node.findChild('EcsService') as ecs.FargateService;
service.desiredCount = ${p.desiredCount || 2};`,

      scale_vertical: (p) =>
        `// Update instance type
const taskDef = stack.node.findChild('TaskDefinition') as ecs.TaskDefinition;
taskDef.cpu = ${p.cpu || 512};
taskDef.memoryMiB = ${p.memory || 1024};`,

      update_env_var: (p) =>
        `// Update environment variable
const container = taskDef.defaultContainer;
container.addEnvironment('${p.key}', '${p.value}');`,

      rotate_secret: (p) =>
        `// Rotate secret
const secret = new secretsmanager.Secret(stack, 'RotatedSecret', {
  secretName: '${p.secretName}',
  generateSecretString: {
    secretStringTemplate: JSON.stringify({ username: '${p.username}' }),
    generateStringKey: 'password',
  },
});`,

      add_tool: (p) =>
        `// Add new tool
const tool = new ChimeraTool(stack, '${p.toolName}', {
  name: '${p.toolName}',
  description: '${p.description}',
  handler: '${p.handler}',
});`,

      update_config: (p) =>
        `// Update configuration
const config = ssm.StringParameter.fromStringParameterName(
  stack,
  'Config',
  '/chimera/${proposal.tenantId}/config'
);
config.stringValue = JSON.stringify(${JSON.stringify(p.config)});`,
    };

    const template = changeTypeTemplates[proposal.changeType];
    return template ? template(proposal.parameters) : '// No changes';
  }

  private async getMainHead(): Promise<string> {
    const result = await this.codecommit.send(
      new GetBranchCommand({
        repositoryName: this.repositoryName,
        branchName: 'main',
      })
    );

    return result.branch?.commitId || '';
  }

  private async restartRuntime(runtimeId: string): Promise<{ success: boolean; message: string }> {
    // Placeholder: Would use ECS or Lambda APIs to restart runtime
    console.log(`Restarting runtime: ${runtimeId}`);
    return {
      success: true,
      message: `Runtime ${runtimeId} restarted successfully`,
    };
  }

  private async clearCache(runtimeId: string): Promise<{ success: boolean; message: string }> {
    // Placeholder: Would clear ElastiCache or in-memory cache
    console.log(`Clearing cache for runtime: ${runtimeId}`);
    return {
      success: true,
      message: `Cache cleared for runtime ${runtimeId}`,
    };
  }

  private async resetSession(runtimeId: string): Promise<{ success: boolean; message: string }> {
    // Placeholder: Would reset session state in DynamoDB
    console.log(`Resetting session for runtime: ${runtimeId}`);
    return {
      success: true,
      message: `Session reset for runtime ${runtimeId}`,
    };
  }
}

/**
 * Create an infrastructure modifier instance
 */
export function createInfrastructureModifier(params: {
  repositoryName: string;
  safetyHarness: EvolutionSafetyHarness;
}): InfrastructureModifier {
  return new InfrastructureModifier(params);
}
