/**
 * Unit tests for AutoSkillGenerator
 *
 * Tests skill generation from detected tool patterns.
 * DynamoDB-dependent paths (detectRepeatedPatterns, publishSkill, getAutoGeneratedSkills)
 * are tested using mock DynamoDB send.
 *
 * Note: generateSkillFromPattern and testSkillInSandbox are pure/stub functions
 * that do not call AWS services — tested directly.
 */

import { describe, it, expect } from 'bun:test';
import { createAutoSkillGenerator } from '../auto-skill-gen';
import type { ToolPattern } from '../types';

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

function makePattern(pattern: string[], occurrences = 4): ToolPattern {
  return {
    pattern,
    occurrences,
    steps: pattern.length,
    exampleFullSequence: [...pattern],
    confidence: Math.min(occurrences * 0.1, 0.99),
  };
}

function makeGenerator() {
  return createAutoSkillGenerator({
    sessionsTable: 'test-sessions',
    evolutionTable: 'test-evolution',
    artifactsBucket: 'test-bucket',
  });
}

// ---------------------------------------------------------------------------
// generateSkillFromPattern — no AWS calls
// ---------------------------------------------------------------------------

describe('AutoSkillGenerator.generateSkillFromPattern', () => {
  it('generates a skill with correct metadata', async () => {
    const gen = makeGenerator();
    const pattern = makePattern(['read_file', 'edit_file', 'run_tests']);

    const result = await gen.generateSkillFromPattern({
      pattern,
      tenantId: 'acme',
    });

    expect(result.skillName).toBeTruthy();
    expect(result.pattern).toEqual(pattern.pattern);
    expect(result.confidence).toBe(pattern.confidence);
    expect(result.metadata.tenantId).toBe('acme');
    expect(result.metadata.occurrences).toBe(4);
  });

  it('generates a SKILL.md that references all tools in the pattern', async () => {
    const gen = makeGenerator();
    const pattern = makePattern(['search_code', 'read_file', 'edit_file']);

    const result = await gen.generateSkillFromPattern({
      pattern,
      tenantId: 'acme',
    });

    for (const tool of pattern.pattern) {
      expect(result.skillMd).toContain(tool);
    }
  });

  it('includes tenant ID and generation metadata in SKILL.md', async () => {
    const gen = makeGenerator();
    const pattern = makePattern(['list_files', 'read_file']);

    const result = await gen.generateSkillFromPattern({
      pattern,
      tenantId: 'my-tenant',
    });

    expect(result.skillMd).toContain('my-tenant');
    expect(result.skillMd).toContain('Auto-generated');
  });

  it('generates a unique skill name from single-tool patterns', async () => {
    const gen = makeGenerator();
    const pattern = makePattern(['bash_tool', 'bash_tool', 'bash_tool'], 5);

    const result = await gen.generateSkillFromPattern({
      pattern,
      tenantId: 'acme',
    });

    expect(result.skillName).toBeTruthy();
    expect(typeof result.skillName).toBe('string');
  });

  it('handles two-tool patterns', async () => {
    const gen = makeGenerator();
    const pattern = makePattern(['read_file', 'write_file'], 3);

    const result = await gen.generateSkillFromPattern({
      pattern,
      tenantId: 'acme',
    });

    expect(result.skillMd).toContain('read_file');
    expect(result.skillMd).toContain('write_file');
  });

  it('handles multi-step patterns with 5+ tools', async () => {
    const gen = makeGenerator();
    const pattern = makePattern(
      ['search_code', 'read_file', 'edit_file', 'run_tests', 'git_commit'],
      6
    );

    const result = await gen.generateSkillFromPattern({
      pattern,
      tenantId: 'acme',
    });

    expect(result.skillMd).toContain('git_commit');
  });
});

// ---------------------------------------------------------------------------
// testSkillInSandbox — placeholder implementation
// ---------------------------------------------------------------------------

describe('AutoSkillGenerator.testSkillInSandbox', () => {
  it('returns correct shape with totalTests matching input count', async () => {
    const gen = makeGenerator();

    const result = await gen.testSkillInSandbox({
      skillMd: '# My Skill\n\nDo something.',
      testInputs: ['input1', 'input2'],
    });

    expect(result.totalTests).toBe(2);
    expect(result.passed + result.failed).toBe(2);
    expect(result.results).toHaveLength(2);
  });

  it('returns all-zero counts for empty test inputs', async () => {
    const gen = makeGenerator();

    const result = await gen.testSkillInSandbox({
      skillMd: '# Skill\n\nContent.',
      testInputs: [],
    });

    expect(result.totalTests).toBe(0);
    expect(result.passed).toBe(0);
    expect(result.failed).toBe(0);
  });

  it('accepts optional toolCode parameter', async () => {
    const gen = makeGenerator();

    const result = await gen.testSkillInSandbox({
      skillMd: '# Skill',
      toolCode: 'function run() {}',
      testInputs: ['test'],
    });

    expect(result.totalTests).toBe(1);
    expect(result.results).toHaveLength(1);
  });
});
